#!/bin/sh
# Mongo C Driver uninstall program, generated with CMake
# Copyright 2018-present MongoDB, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

save_pwd=$(pwd)
cd /home/hitanshu/mongo-cc/

printf "Removing file "share/mongo-cxx-driver/LICENSE""
(rm -f "share/mongo-cxx-driver/LICENSE" && printf "\n") || printf " ... not removed\n"
printf "Removing file "share/mongo-cxx-driver/README.md""
(rm -f "share/mongo-cxx-driver/README.md" && printf "\n") || printf " ... not removed\n"
printf "Removing file "share/mongo-cxx-driver/THIRD-PARTY-NOTICES""
(rm -f "share/mongo-cxx-driver/THIRD-PARTY-NOTICES" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/bsoncxx/v_noabi/bsoncxx/builder/stream/closed_context.hpp""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/builder/stream/closed_context.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/bsoncxx/v_noabi/bsoncxx/builder/stream/value_context.hpp""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/builder/stream/value_context.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/bsoncxx/v_noabi/bsoncxx/builder/stream/array.hpp""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/builder/stream/array.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/bsoncxx/v_noabi/bsoncxx/builder/stream/key_context.hpp""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/builder/stream/key_context.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/bsoncxx/v_noabi/bsoncxx/builder/stream/single_context.hpp""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/builder/stream/single_context.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/bsoncxx/v_noabi/bsoncxx/builder/stream/array_context.hpp""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/builder/stream/array_context.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/bsoncxx/v_noabi/bsoncxx/builder/stream/document.hpp""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/builder/stream/document.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/bsoncxx/v_noabi/bsoncxx/builder/stream/helpers.hpp""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/builder/stream/helpers.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/bsoncxx/v_noabi/bsoncxx/builder/core.hpp""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/builder/core.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/bsoncxx/v_noabi/bsoncxx/builder/basic/array.hpp""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/builder/basic/array.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/bsoncxx/v_noabi/bsoncxx/builder/basic/sub_array.hpp""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/builder/basic/sub_array.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/bsoncxx/v_noabi/bsoncxx/builder/basic/sub_document.hpp""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/builder/basic/sub_document.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/bsoncxx/v_noabi/bsoncxx/builder/basic/document.hpp""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/builder/basic/document.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/bsoncxx/v_noabi/bsoncxx/builder/basic/helpers.hpp""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/builder/basic/helpers.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/bsoncxx/v_noabi/bsoncxx/builder/basic/kvp.hpp""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/builder/basic/kvp.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/bsoncxx/v_noabi/bsoncxx/builder/basic/impl.hpp""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/builder/basic/impl.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/bsoncxx/v_noabi/bsoncxx/builder/concatenate.hpp""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/builder/concatenate.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/bsoncxx/v_noabi/bsoncxx/array/value.hpp""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/array/value.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/bsoncxx/v_noabi/bsoncxx/array/view_or_value.hpp""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/array/view_or_value.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/bsoncxx/v_noabi/bsoncxx/array/element.hpp""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/array/element.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/bsoncxx/v_noabi/bsoncxx/array/view.hpp""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/array/view.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/bsoncxx/v_noabi/bsoncxx/string/view_or_value.hpp""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/string/view_or_value.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/bsoncxx/v_noabi/bsoncxx/string/to_string.hpp""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/string/to_string.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/bsoncxx/v_noabi/bsoncxx/types.hpp""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/types.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/bsoncxx/v_noabi/bsoncxx/oid.hpp""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/oid.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/bsoncxx/v_noabi/bsoncxx/util/functor.hpp""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/util/functor.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/bsoncxx/v_noabi/bsoncxx/exception/exception.hpp""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/exception/exception.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/bsoncxx/v_noabi/bsoncxx/exception/error_code.hpp""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/exception/error_code.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/bsoncxx/v_noabi/bsoncxx/view_or_value.hpp""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/view_or_value.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/bsoncxx/v_noabi/bsoncxx/decimal128.hpp""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/decimal128.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/bsoncxx/v_noabi/bsoncxx/types/bson_value/make_value.hpp""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/types/bson_value/make_value.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/bsoncxx/v_noabi/bsoncxx/types/bson_value/value.hpp""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/types/bson_value/value.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/bsoncxx/v_noabi/bsoncxx/types/bson_value/view_or_value.hpp""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/types/bson_value/view_or_value.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/bsoncxx/v_noabi/bsoncxx/types/bson_value/view.hpp""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/types/bson_value/view.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/bsoncxx/v_noabi/bsoncxx/document/value.hpp""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/document/value.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/bsoncxx/v_noabi/bsoncxx/document/view_or_value.hpp""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/document/view_or_value.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/bsoncxx/v_noabi/bsoncxx/document/element.hpp""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/document/element.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/bsoncxx/v_noabi/bsoncxx/document/view.hpp""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/document/view.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/bsoncxx/v_noabi/bsoncxx/json.hpp""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/json.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/bsoncxx/v_noabi/bsoncxx/enums/type.hpp""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/enums/type.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/bsoncxx/v_noabi/bsoncxx/enums/binary_sub_type.hpp""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/enums/binary_sub_type.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/bsoncxx/v_noabi/bsoncxx/stdx/string_view.hpp""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/stdx/string_view.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/bsoncxx/v_noabi/bsoncxx/stdx/make_unique.hpp""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/stdx/make_unique.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/bsoncxx/v_noabi/bsoncxx/stdx/optional.hpp""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/stdx/optional.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/bsoncxx/v_noabi/bsoncxx/config/prelude.hpp""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/config/prelude.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/bsoncxx/v_noabi/bsoncxx/config/postlude.hpp""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/config/postlude.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/bsoncxx/v_noabi/bsoncxx/config/compiler.hpp""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/config/compiler.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/bsoncxx/v_noabi/bsoncxx/validate.hpp""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/validate.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/bsoncxx/v_noabi/bsoncxx/config/export.hpp""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/config/export.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "lib/cmake/libbsoncxx-3.6.0/libbsoncxx-config.cmake""
(rm -f "lib/cmake/libbsoncxx-3.6.0/libbsoncxx-config.cmake" && printf "\n") || printf " ... not removed\n"
printf "Removing file "lib/cmake/libbsoncxx-3.6.0/libbsoncxx-config-version.cmake""
(rm -f "lib/cmake/libbsoncxx-3.6.0/libbsoncxx-config-version.cmake" && printf "\n") || printf " ... not removed\n"
printf "Removing file "lib/libbsoncxx.so.3.6.0""
(rm -f "lib/libbsoncxx.so.3.6.0" && printf "\n") || printf " ... not removed\n"
printf "Removing file "lib/libbsoncxx.so._noabi""
(rm -f "lib/libbsoncxx.so._noabi" && printf "\n") || printf " ... not removed\n"
printf "Removing file "lib/libbsoncxx.so""
(rm -f "lib/libbsoncxx.so" && printf "\n") || printf " ... not removed\n"
printf "Removing file "lib/cmake/bsoncxx-3.6.0/bsoncxx_targets.cmake""
(rm -f "lib/cmake/bsoncxx-3.6.0/bsoncxx_targets.cmake" && printf "\n") || printf " ... not removed\n"
printf "Removing file "lib/cmake/bsoncxx-3.6.0/bsoncxx_targets-release.cmake""
(rm -f "lib/cmake/bsoncxx-3.6.0/bsoncxx_targets-release.cmake" && printf "\n") || printf " ... not removed\n"
printf "Removing file "lib/cmake/bsoncxx-3.6.0/bsoncxx-config-version.cmake""
(rm -f "lib/cmake/bsoncxx-3.6.0/bsoncxx-config-version.cmake" && printf "\n") || printf " ... not removed\n"
printf "Removing file "lib/cmake/bsoncxx-3.6.0/bsoncxx-config.cmake""
(rm -f "lib/cmake/bsoncxx-3.6.0/bsoncxx-config.cmake" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/bsoncxx/v_noabi/bsoncxx/config/config.hpp""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/config/config.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/bsoncxx/v_noabi/bsoncxx/config/version.hpp""
(rm -f "include/bsoncxx/v_noabi/bsoncxx/config/version.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "lib/pkgconfig/libbsoncxx.pc""
(rm -f "lib/pkgconfig/libbsoncxx.pc" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/logger.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/logger.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/cursor.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/cursor.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/stdx.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/stdx.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/result/replace_one.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/result/replace_one.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/result/bulk_write.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/result/bulk_write.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/result/delete.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/result/delete.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/result/gridfs/upload.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/result/gridfs/upload.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/result/insert_one.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/result/insert_one.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/result/insert_many.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/result/insert_many.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/result/update.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/result/update.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/events/command_failed_event.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/events/command_failed_event.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/events/server_opening_event.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/events/server_opening_event.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/events/topology_closed_event.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/events/topology_closed_event.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/events/heartbeat_succeeded_event.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/events/heartbeat_succeeded_event.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/events/topology_description.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/events/topology_description.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/events/heartbeat_failed_event.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/events/heartbeat_failed_event.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/events/command_started_event.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/events/command_started_event.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/events/topology_changed_event.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/events/topology_changed_event.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/events/server_description.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/events/server_description.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/events/topology_opening_event.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/events/topology_opening_event.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/events/heartbeat_started_event.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/events/heartbeat_started_event.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/events/server_changed_event.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/events/server_changed_event.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/events/server_closed_event.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/events/server_closed_event.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/events/command_succeeded_event.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/events/command_succeeded_event.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/client.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/client.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/instance.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/instance.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/collection.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/collection.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/bulk_write.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/bulk_write.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/exception/operation_exception.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/exception/operation_exception.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/exception/exception.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/exception/exception.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/exception/logic_error.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/exception/logic_error.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/exception/error_code.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/exception/error_code.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/exception/gridfs_exception.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/exception/gridfs_exception.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/exception/authentication_exception.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/exception/authentication_exception.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/exception/query_exception.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/exception/query_exception.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/exception/server_error_code.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/exception/server_error_code.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/exception/write_exception.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/exception/write_exception.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/exception/bulk_write_exception.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/exception/bulk_write_exception.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/model/replace_one.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/model/replace_one.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/model/write.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/model/write.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/model/delete_many.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/model/delete_many.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/model/delete_one.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/model/delete_one.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/model/update_many.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/model/update_many.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/model/insert_one.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/model/insert_one.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/model/update_one.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/model/update_one.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/options/transaction.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/transaction.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/options/client.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/client.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/options/find_one_and_update.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/find_one_and_update.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/options/find.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/find.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/options/create_collection.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/create_collection.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/options/find_one_and_delete.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/find_one_and_delete.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/options/bulk_write.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/bulk_write.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/options/encrypt.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/encrypt.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/options/aggregate.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/aggregate.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/options/apm.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/apm.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/options/data_key.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/data_key.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/options/delete.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/delete.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/options/auto_encryption.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/auto_encryption.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/options/insert.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/insert.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/options/count.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/count.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/options/tls.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/tls.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/options/gridfs/bucket.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/gridfs/bucket.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/options/gridfs/upload.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/gridfs/upload.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/options/estimated_document_count.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/estimated_document_count.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/options/change_stream.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/change_stream.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/options/index.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/index.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/options/client_encryption.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/client_encryption.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/options/pool.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/pool.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/options/distinct.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/distinct.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/options/find_one_common_options.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/find_one_common_options.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/options/ssl.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/ssl.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/options/find_one_and_replace.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/find_one_and_replace.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/options/update.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/update.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/options/client_session.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/client_session.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/options/index_view.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/index_view.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/options/replace.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/options/replace.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/read_concern.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/read_concern.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/hint.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/hint.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/index_model.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/index_model.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/gridfs/bucket.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/gridfs/bucket.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/gridfs/downloader.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/gridfs/downloader.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/gridfs/uploader.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/gridfs/uploader.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/uri.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/uri.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/change_stream.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/change_stream.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/client_encryption.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/client_encryption.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/validation_criteria.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/validation_criteria.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/database.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/database.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/pipeline.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/pipeline.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/write_concern.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/write_concern.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/pool.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/pool.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/config/prelude.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/config/prelude.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/config/postlude.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/config/postlude.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/config/compiler.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/config/compiler.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/read_preference.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/read_preference.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/client_session.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/client_session.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/index_view.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/index_view.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/write_type.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/write_type.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/config/export.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/config/export.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "lib/cmake/libmongocxx-3.6.0/libmongocxx-config.cmake""
(rm -f "lib/cmake/libmongocxx-3.6.0/libmongocxx-config.cmake" && printf "\n") || printf " ... not removed\n"
printf "Removing file "lib/cmake/libmongocxx-3.6.0/libmongocxx-config-version.cmake""
(rm -f "lib/cmake/libmongocxx-3.6.0/libmongocxx-config-version.cmake" && printf "\n") || printf " ... not removed\n"
printf "Removing file "lib/libmongocxx.so.3.6.0""
(rm -f "lib/libmongocxx.so.3.6.0" && printf "\n") || printf " ... not removed\n"
printf "Removing file "lib/libmongocxx.so._noabi""
(rm -f "lib/libmongocxx.so._noabi" && printf "\n") || printf " ... not removed\n"
printf "Removing file "lib/libmongocxx.so""
(rm -f "lib/libmongocxx.so" && printf "\n") || printf " ... not removed\n"
printf "Removing file "lib/cmake/mongocxx-3.6.0/mongocxx_targets.cmake""
(rm -f "lib/cmake/mongocxx-3.6.0/mongocxx_targets.cmake" && printf "\n") || printf " ... not removed\n"
printf "Removing file "lib/cmake/mongocxx-3.6.0/mongocxx_targets-release.cmake""
(rm -f "lib/cmake/mongocxx-3.6.0/mongocxx_targets-release.cmake" && printf "\n") || printf " ... not removed\n"
printf "Removing file "lib/cmake/mongocxx-3.6.0/mongocxx-config-version.cmake""
(rm -f "lib/cmake/mongocxx-3.6.0/mongocxx-config-version.cmake" && printf "\n") || printf " ... not removed\n"
printf "Removing file "lib/cmake/mongocxx-3.6.0/mongocxx-config.cmake""
(rm -f "lib/cmake/mongocxx-3.6.0/mongocxx-config.cmake" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/config/config.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/config/config.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "include/mongocxx/v_noabi/mongocxx/config/version.hpp""
(rm -f "include/mongocxx/v_noabi/mongocxx/config/version.hpp" && printf "\n") || printf " ... not removed\n"
printf "Removing file "lib/pkgconfig/libmongocxx.pc""
(rm -f "lib/pkgconfig/libmongocxx.pc" && printf "\n") || printf " ... not removed\n"
printf "Removing file "share/mongo-cxx-driver/uninstall.sh""
(rm -f "share/mongo-cxx-driver/uninstall.sh" && printf "\n") || printf " ... not removed\n"
printf "Removing directory "share/mongo-cxx-driver\nshare\nshare/mongo-cxx-driver\nshare\nshare/mongo-cxx-driver\nshare\ninclude/bsoncxx/v_noabi/bsoncxx/builder/stream\ninclude/bsoncxx/v_noabi/bsoncxx/builder\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/builder/stream\ninclude/bsoncxx/v_noabi/bsoncxx/builder\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/builder/stream\ninclude/bsoncxx/v_noabi/bsoncxx/builder\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/builder/stream\ninclude/bsoncxx/v_noabi/bsoncxx/builder\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/builder/stream\ninclude/bsoncxx/v_noabi/bsoncxx/builder\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/builder/stream\ninclude/bsoncxx/v_noabi/bsoncxx/builder\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/builder/stream\ninclude/bsoncxx/v_noabi/bsoncxx/builder\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/builder/stream\ninclude/bsoncxx/v_noabi/bsoncxx/builder\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/builder\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/builder/basic\ninclude/bsoncxx/v_noabi/bsoncxx/builder\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/builder/basic\ninclude/bsoncxx/v_noabi/bsoncxx/builder\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/builder/basic\ninclude/bsoncxx/v_noabi/bsoncxx/builder\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/builder/basic\ninclude/bsoncxx/v_noabi/bsoncxx/builder\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/builder/basic\ninclude/bsoncxx/v_noabi/bsoncxx/builder\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/builder/basic\ninclude/bsoncxx/v_noabi/bsoncxx/builder\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/builder/basic\ninclude/bsoncxx/v_noabi/bsoncxx/builder\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/builder\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/array\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/array\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/array\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/array\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/string\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/string\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/util\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/exception\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/exception\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/types/bson_value\ninclude/bsoncxx/v_noabi/bsoncxx/types\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/types/bson_value\ninclude/bsoncxx/v_noabi/bsoncxx/types\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/types/bson_value\ninclude/bsoncxx/v_noabi/bsoncxx/types\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/types/bson_value\ninclude/bsoncxx/v_noabi/bsoncxx/types\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/document\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/document\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/document\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/document\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/enums\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/enums\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/stdx\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/stdx\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/stdx\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/config\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/config\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/config\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/config\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\nlib/cmake/libbsoncxx-3.6.0\nlib/cmake\nlib\nlib/cmake/libbsoncxx-3.6.0\nlib/cmake\nlib\nlib\nlib\nlib\nlib/cmake/bsoncxx-3.6.0\nlib/cmake\nlib\nlib/cmake/bsoncxx-3.6.0\nlib/cmake\nlib\nlib/cmake/bsoncxx-3.6.0\nlib/cmake\nlib\nlib/cmake/bsoncxx-3.6.0\nlib/cmake\nlib\ninclude/bsoncxx/v_noabi/bsoncxx/config\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/config\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\nlib/pkgconfig\nlib\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/result\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/result\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/result\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/result/gridfs\ninclude/mongocxx/v_noabi/mongocxx/result\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/result\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/result\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/result\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/events\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/events\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/events\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/events\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/events\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/events\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/events\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/events\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/events\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/events\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/events\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/events\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/events\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/events\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/exception\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/exception\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/exception\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/exception\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/exception\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/exception\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/exception\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/exception\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/exception\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/exception\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/model\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/model\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/model\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/model\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/model\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/model\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/model\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options/gridfs\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options/gridfs\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/gridfs\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/gridfs\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/gridfs\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/config\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/config\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/config\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/config\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\nlib/cmake/libmongocxx-3.6.0\nlib/cmake\nlib\nlib/cmake/libmongocxx-3.6.0\nlib/cmake\nlib\nlib\nlib\nlib\nlib/cmake/mongocxx-3.6.0\nlib/cmake\nlib\nlib/cmake/mongocxx-3.6.0\nlib/cmake\nlib\nlib/cmake/mongocxx-3.6.0\nlib/cmake\nlib\nlib/cmake/mongocxx-3.6.0\nlib/cmake\nlib\ninclude/mongocxx/v_noabi/mongocxx/config\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/config\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\nlib/pkgconfig\nlib\nshare/mongo-cxx-driver\nshare\n""
(rmdir "share/mongo-cxx-driver\nshare\nshare/mongo-cxx-driver\nshare\nshare/mongo-cxx-driver\nshare\ninclude/bsoncxx/v_noabi/bsoncxx/builder/stream\ninclude/bsoncxx/v_noabi/bsoncxx/builder\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/builder/stream\ninclude/bsoncxx/v_noabi/bsoncxx/builder\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/builder/stream\ninclude/bsoncxx/v_noabi/bsoncxx/builder\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/builder/stream\ninclude/bsoncxx/v_noabi/bsoncxx/builder\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/builder/stream\ninclude/bsoncxx/v_noabi/bsoncxx/builder\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/builder/stream\ninclude/bsoncxx/v_noabi/bsoncxx/builder\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/builder/stream\ninclude/bsoncxx/v_noabi/bsoncxx/builder\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/builder/stream\ninclude/bsoncxx/v_noabi/bsoncxx/builder\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/builder\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/builder/basic\ninclude/bsoncxx/v_noabi/bsoncxx/builder\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/builder/basic\ninclude/bsoncxx/v_noabi/bsoncxx/builder\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/builder/basic\ninclude/bsoncxx/v_noabi/bsoncxx/builder\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/builder/basic\ninclude/bsoncxx/v_noabi/bsoncxx/builder\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/builder/basic\ninclude/bsoncxx/v_noabi/bsoncxx/builder\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/builder/basic\ninclude/bsoncxx/v_noabi/bsoncxx/builder\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/builder/basic\ninclude/bsoncxx/v_noabi/bsoncxx/builder\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/builder\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/array\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/array\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/array\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/array\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/string\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/string\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/util\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/exception\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/exception\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/types/bson_value\ninclude/bsoncxx/v_noabi/bsoncxx/types\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/types/bson_value\ninclude/bsoncxx/v_noabi/bsoncxx/types\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/types/bson_value\ninclude/bsoncxx/v_noabi/bsoncxx/types\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/types/bson_value\ninclude/bsoncxx/v_noabi/bsoncxx/types\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/document\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/document\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/document\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/document\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/enums\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/enums\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/stdx\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/stdx\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/stdx\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/config\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/config\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/config\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/config\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\nlib/cmake/libbsoncxx-3.6.0\nlib/cmake\nlib\nlib/cmake/libbsoncxx-3.6.0\nlib/cmake\nlib\nlib\nlib\nlib\nlib/cmake/bsoncxx-3.6.0\nlib/cmake\nlib\nlib/cmake/bsoncxx-3.6.0\nlib/cmake\nlib\nlib/cmake/bsoncxx-3.6.0\nlib/cmake\nlib\nlib/cmake/bsoncxx-3.6.0\nlib/cmake\nlib\ninclude/bsoncxx/v_noabi/bsoncxx/config\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\ninclude/bsoncxx/v_noabi/bsoncxx/config\ninclude/bsoncxx/v_noabi/bsoncxx\ninclude/bsoncxx/v_noabi\ninclude/bsoncxx\ninclude\nlib/pkgconfig\nlib\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/result\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/result\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/result\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/result/gridfs\ninclude/mongocxx/v_noabi/mongocxx/result\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/result\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/result\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/result\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/events\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/events\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/events\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/events\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/events\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/events\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/events\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/events\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/events\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/events\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/events\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/events\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/events\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/events\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/exception\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/exception\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/exception\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/exception\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/exception\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/exception\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/exception\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/exception\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/exception\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/exception\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/model\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/model\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/model\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/model\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/model\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/model\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/model\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options/gridfs\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options/gridfs\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/options\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/gridfs\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/gridfs\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/gridfs\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/config\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/config\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/config\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/config\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\nlib/cmake/libmongocxx-3.6.0\nlib/cmake\nlib\nlib/cmake/libmongocxx-3.6.0\nlib/cmake\nlib\nlib\nlib\nlib\nlib/cmake/mongocxx-3.6.0\nlib/cmake\nlib\nlib/cmake/mongocxx-3.6.0\nlib/cmake\nlib\nlib/cmake/mongocxx-3.6.0\nlib/cmake\nlib\nlib/cmake/mongocxx-3.6.0\nlib/cmake\nlib\ninclude/mongocxx/v_noabi/mongocxx/config\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\ninclude/mongocxx/v_noabi/mongocxx/config\ninclude/mongocxx/v_noabi/mongocxx\ninclude/mongocxx/v_noabi\ninclude/mongocxx\ninclude\nlib/pkgconfig\nlib\nshare/mongo-cxx-driver\nshare\n" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"
cd ..
printf "Removing top-level installation directory: "/home/hitanshu/mongo-cc/""
(rmdir "/home/hitanshu/mongo-cc/" 2>/dev/null && printf "\n") || printf " ... not removed (probably not empty)\n"

# Return to the directory from which the program was called
cd ${save_pwd}
